### ISSUE TITLE
Use HTTP response code for thrown exceptions

### ISSUE THREAD

**Issue by yoosefi** [mivaecommerce/api-sdk-php#3]
When throwing HTTP related exceptions, please use the response code as the exception's code. This will help with debugging and also allow callers to catch/retry if needed.

Example:
https://github.com/mivaecommerce/api-sdk-php/blob/7b61091e16cf85f7c9c351354866234f1af7b3c3/src/BaseClient.php#L310

Pass the HTTP response code in so the exception can be caught and checked.

**Comment by ghassani** [comment]
Created internal issue. Should be resolved on the next release which includes 10.03.00 support.

Reference: MMAPI-54

**Comment by ghassani** [comment]
Fixed in 2.1.0.
ClientException now includes the http response object if one was received. You can access it via the getHttpResponse() method in ClientException
