### ISSUE TITLE
v2.2.0 :: Product no longer automatically set in ProductVariantGenerateDelimiter

### ISSUE THREAD

**Issue by TipPro** [mivaecommerce/api-sdk-php#4]
https://github.com/mivaecommerce/api-sdk-php/blob/c531105da2b6c78d20c22e7f1ddeffce158b3ef8/src/Request/ProductVariantGenerateDelimiter.php#L41-L46

In 2.2.0 the product is no longer set nor is it passed through in the constructor.

**Comment by ghassani** [comment]
Thank you for reporting the issue. I have filed a bug for this in our internal tracker. You can reference issue number `MMAPI-75`

**Comment by ghassani** [comment]
Fixed in 2.2.1 release
