### ISSUE TITLE
In PHP 8 is_resource() returns false

### ISSUE THREAD

**Issue by TipPro** [mivaecommerce/api-sdk-php#5]
https://github.com/mivaecommerce/api-sdk-php/blob/c531105da2b6c78d20c22e7f1ddeffce158b3ef8/src/Http/HttpClient.php#L138-L140

This **if** statement needs to be updated to be compatible with PHP 8.  Consider using `if ($handle === false)` instead. 

More information can be found here: https://php.watch/versions/8.0/resource-CurlHandle

**Comment by ghassani** [comment]
Thank you for another report. I have filed this in our internal tracker, reference MMAPI-76

**Comment by yoosefi** [comment]
@ghassani PHP 7.4 is end of life as of today, please make your library 8.1 compatible ASAP.

**Comment by ghassani** [comment]
I have addressed this issue in the 2.2.1 release. The next major release will have a more complete update for PHP8 support but this should get your client working in the meantime.
