### ISSUE TITLE
error Decoding JSON: Single unpaired UTF-16 surrogate in unicode escape

### ISSUE THREAD

**Issue by snnyk** [mivaecommerce/api-sdk-php#6]
I always get this error on the same page while paginating.

**error Decoding JSON: Single unpaired UTF-16 surrogate in unicode escape**

```
$request = new CustomerListLoadQuery($client);

    try {
        $response = $request->send();
    } catch(ClientException $e) {
        echo $e->getMessage();
    }
```

**Comment by ghassani** [comment]
It seems you may have some corrupted encoding somewhere in your customer database. We do have a module that can correct these types of issues in some cases however before suggesting that I would like to verify there is a data corruption somewhere.

What you could try to do in your sample code provided is dump the http response from the thrown exception and try to narrow down the offending record and further inspect it that it does have corrupted encoding.

`
    $request = new CustomerListLoadQuery($client);

    try {
        $response = $request->send();
    } catch(ClientException $e) {
        echo $e->getMessage();

        if ($e->getHttpResponse())
        {
            var_dump($e->getHttpResponse()->getContent());
        }
    }
`



If you are going to include any data here in this report, please ensure that it does not contain any personal or sensitive customer or store information. If you wish to provide data for further inspection and it cannot be stripped of identifying information then please open a support ticket to securely transfer that to us.

**Comment by snnyk** [comment]
I've already looked into this and have plenty of corrupt data into shipping and billing details.
Is there a function in SDK where I can get data safely?

**Comment by yoosefi** [comment]
@snnyk i have the same problem. my solution is to use a small page size and skip over bad pages.

**Comment by ghassani** [comment]
I would suggest both of you open up a ticket with support and request them to install and run our **latin1toutf8** module. This can correct these types of issues.

In the meantime I will look further into the issue and see if there is something that can be modified on the SDK end to allow for pulling the data without issue.

**Comment by yoosefi** [comment]
@ghassani in my case the database is out of my control. GIGO.

**Comment by ghassani** [comment]
v2.3.0 added a new client option,`json_decode_flags`, set it with encode flags outlined here https://www.php.net/manual/en/function.json-decode.php

example: 

`$client->setOption('json_decode_flags', JSON_THROW_ON_ERROR | JSON_INVALID_UTF8_IGNORE);`
