### ISSUE TITLE
Missing "->send()" in example

### ISSUE THREAD

**Issue by TipPro** [mivaecommerce/api-sdk-php#8]
https://github.com/mivaecommerce/api-sdk-php/blob/1955b3fde4c22dcb6a1181ee0f1fe43ddff0a5fc/examples/LoadAndEditProductExample.php#L50

Noticed a typo in this example.

**Comment by ghassani** [comment]
Thank You

Internal Issue: MMAPI-174

**Comment by ghassani** [comment]
Fixed in 2.4.0
